version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sorting_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"  # Access pgAdmin on port 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data

  app:
    build: .
    container_name: sorting_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/sorting_db
    volumes:
      - .:/app
    command: python main.py

volumes:
  pg_data:
  pgadmin_data:
